branches:
  only:
    - gh-pages
language: ruby
rvm:
  - 2.5
script: ruby ./appage.rb
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: gh-pages
