---

language: ruby

rvm:
  - 2.5

script:
  - gem install bundler:1.17.3
  - ruby ./generate-loki.rb
  - ruby ./generate-juno.rb

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: gh-pages
