---
title: elementary AppCenter
separator: "&sdot;"
color:
  primary: "#4c158a"
  primary-text: "#fff"

baseurl: ''

collections:
  apps:
    title: Apps
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: ""
      type: apps
    values:
      layout: app

markdown: kramdown

permalink: pretty
sass:
  style: compressed
